name       : tesseract
version    : 3.04.01
release    : 3
source     :
    - https://github.com/tesseract-ocr/tesseract/archive/3.04.01.tar.gz : 57f63e1b14ae04c3932a2683e4be4954a2849e17edd638ffe91bc5a2156adc6a
license    : Apache-2.0
component  : office
summary    : Tesseract Open Source OCR Engine
description: |
    Tesseract Open Source OCR Engine
builddeps  :
    - pkgconfig(lept)
rundeps    :
    - tessdata
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
