name       : tesseract
version    : 4.0.0
release    : 7
source     :
    - https://github.com/tesseract-ocr/tesseract/archive/4.0.0.tar.gz : a1f5422ca49a32e5f35c54dee5112b11b99928fc9f4ee6695cdc6768d69f61dd
license    : Apache-2.0
component  : office
summary    : Tesseract Open Source OCR Engine
description: |
    Tesseract Open Source OCR Engine
builddeps  :
    - pkgconfig(lept)
rundeps    :
    - tessdata
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
