name       : tesseract
version    : 5.1.0
release    : 12
source     :
    - https://github.com/tesseract-ocr/tesseract/archive/refs/tags/5.1.0.tar.gz : fdec8528d5a0ecc28ab5fff985e0b8ced60726f6ef33f54126f2868e323d4bd2
homepage   : https://tesseract-ocr.github.io/
license    : Apache-2.0
component  : office
summary    : Tesseract Open Source OCR Engine
description: |
    Tesseract is an open source text recognition (OCR) Engine.
builddeps  :
    - pkgconfig(lept)
rundeps    :
    - tessdata
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
