name       : tesseract
version    : 4.1.1
release    : 8
source     :
    - https://github.com/tesseract-ocr/tesseract/archive/4.1.1.tar.gz : 2a66ff0d8595bff8f04032165e6c936389b1e5727c3ce5a27b3e059d218db1cb
license    : Apache-2.0
component  : office
summary    : Tesseract Open Source OCR Engine
description: |
    Tesseract Open Source OCR Engine
builddeps  :
    - pkgconfig(lept)
rundeps    :
    - tessdata
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
