name       : tesseract
version    : 5.2.0
release    : 13
source     :
    - https://github.com/tesseract-ocr/tesseract/archive/refs/tags/5.2.0.tar.gz : eba4deb2f92a3f89a6623812074af8c53b772079525b3c263aa70bbf7b748b3c
homepage   : https://tesseract-ocr.github.io/
license    : Apache-2.0
component  : office
summary    : Tesseract Open Source OCR Engine
description: |
    Tesseract is an open source text recognition (OCR) Engine.
builddeps  :
    - pkgconfig(lept)
rundeps    :
    - tessdata
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
