name       : tesseract
version    : 3.05.02
release    : 5
source     :
    - https://github.com/tesseract-ocr/tesseract/archive/3.05.02.tar.gz : 494d64ffa7069498a97b909a0e65a35a213989e0184f1ea15332933a90d43445
license    : Apache-2.0
component  : office
summary    : Tesseract Open Source OCR Engine
description: |
    Tesseract Open Source OCR Engine
builddeps  :
    - pkgconfig(lept)
rundeps    :
    - tessdata
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
