name       : tesseract
version    : 5.3.0
release    : 14
source     :
    - https://github.com/tesseract-ocr/tesseract/archive/refs/tags/5.3.0.tar.gz : 7e70870f8341e5ea228af2836ce79a36eefa11b01b56177b4a8997f330c014b8
homepage   : https://tesseract-ocr.github.io/
license    : Apache-2.0
component  : office
summary    : Tesseract Open Source OCR Engine
description: |
    Tesseract is an open source text recognition (OCR) Engine.
builddeps  :
    - pkgconfig(lept)
rundeps    :
    - tessdata
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
